#!/bin/bash
#####################################################################################################
## createResource
## DESCRIPTION: Creates a resource folder for an experiment in XNAT. This is a top-level resource
##				directory, not a scan-level directory.
## AUTHOR: Shaney Flores, Washington University in St. Louis
####################################################################################################
VERSION=1.0
if [ "$1" = "-version" ]; then
	echo 'v'$VERSION
	exit 0
fi

manpage() {
	echo "USAGE: createResource [-i|-id] experiment_id [-t|-token] alias secret [-r] resource [-s|-site] xnat_site [-p|-params] filename"
	echo "EX: createResource -i CNDA_E12345 -t abc123 zyx987 -r RawData -s cnda.wustl.edu -p rawdata.params"
	echo ""
	echo "   -i|-id          REQUIRED. CNDA identiers: Experiment Accession ID"
	echo "   -t|-token       REQUIRED. alias:secret tokens from https://xnat_site/data/services/tokens/issue"
	echo "   -r              REQUIRED. name of resource file to create"
	echo "   -s|-site        REQUIRED. XNAT site address (e.g., cnda.wustl.edu or fornix.wustl.edu)"
	echo "   -p|-params      OPTIONAL. file containing additional parameters for curl call (e.g., \"?content=RAW&format=RawData\")"
	echo ""
	exit 0
}

if [[ $# -eq 0 ]]; then
	manpage
else
	while [[ $# -gt 0 ]]; do
		case "$1" in 
			-i|-id)
			session="$2"
			;;
			-t|-token)
			user_alias="$2"
			user_secret="$3"
			;;
			-r)
			resource="$2"
			;;
			-s|-site)
			site="$2"
			;;
			-p|-params)
			params_file="$2"
			;;
		esac
		shift
	done

	if [ -z "$session" ] || [ -z "$site" ] || [ -z "$user_alias" ] || [ -z "$user_secret" ] || [ -z "$resource" ]; then
		manpage
	fi

	if [ -z "$params_file" ]; then
		addl_params=""
	else
		addl_params=$( <${params_file} )
	fi

	printf " Creating Resource folder: $resource ... "

	# Create experiment resource
	curl -s -k -u ${user_alias}:${user_secret} -X PUT "https://${site}/data/experiments/${session}/resources/${resource}${addl_params}"
	printf "\n"

fi
