#!/bin/bash
#####################################################################################################
## uploadRawImg
## DESCRIPTION: Uploads raw DICOM images for specified subject into the CNDA, bypassing prearchive
## AUTHOR: Shaney Flores, Washington University in St. Louis
#####################################################################################################
VERSION=1.0
if [ "$1" = "-version" ]; then
	echo 'v'$VERSION
	exit 0
fi

manpage() {
	echo "USAGE: uploadRawImg [-i|-id] project_id subject_id experiment_id [-f|-file] session_file [-s|-site] xnat_site [-t|-token] alias secret"
	echo "EX: uploadRawImg -i CCIR_00675 SUBJ001 SUBJ001_MR -f SUBJ001_MR.zip -s fornix.wustl.edu -t abc123 zyx987"
	echo ""
	echo "   -i|-id          REQUIRED. CNDA identiers: Project Label, Subject ID, Experiment ID"
	echo "   -f|-file        REQUIRED. name of zip file of image files to upload"
	echo "   -s|-site        REQUIRED. XNAT site address (e.g., cnda.wustl.edu or fornix.wustl.edu)"
	echo "   -t|-token       REQUIRED. alias:secret tokens from https://xnat_site/data/services/tokens/issue"
	echo ""
	echo "N.B. XNAT is configured to parse DICOM files at upload to populate fields like scan date and scanner model. XNAT will produce an error if"
	echo "     given a NIFTI image. To upload a NIFTI, create a resource folder under a scan and then upload the NIFTI to that folder."
	exit 0
}

if [[ $# -eq 0 ]]; then
	manpage
else
	while [[ $# -gt 0 ]]; do
		case "$1" in
			-i|-id)
			proj="$2"
			subj="$3"
			session="$4"
			;;
			-f|-file)
			session_file="$2"
			;;
			-s|-site)
			site="$2"
			;;
			-t|-token)
			user_alias="$2"
			user_secret="$3"
			;;
		esac
		shift
	done

	if [ -z "$proj" ] || [ -z "$subj" ] || [ -z "$session" ] || [ -z "$session_file" ] || [ -z "$site" ] || [ -z "$user_alias" ] || [ -z "$user_secret" ]; then
		manpage
	fi

	printf " Uploading raw images for $( basename $session_file ) ... "

	# upload raw DICOM image
	curl -s -k -u ${user_alias}:${user_secret} --data-binary @"${session_file}" "https://${site}/data/services/import?PROJECT_ID=${proj}&SUBJECT_ID=${subj}&EXPT_LABEL=${session}&overwrite=append&prearchive=false&inbody=true&extract=true" -H Content-Type:application/zip
	printf "\n"

fi
